### ISSUE TITLE
[iOS] can't save game

### ISSUE THREAD

**Issue by MilarvozM** [alexbatalov/fallout1-ce#219]
On iPad mini 6 iOS 17.7.2, no matter what save name I wanted to give, I always get "Error saving game! Unable to save game." message.

**Comment by process-ontology** [comment]
I"m getting this on Linux. You figure it out?

**Comment by roustam** [comment]
March 2024 (version 1.1) has got this issue on Linux on x64 version.
However, I tested February 2023 (version 1.0) x64 version , it can successfully save the game. 
Please investigate the issue.

**Comment by public-space** [comment]
@roustam Thanks for the info. I ended up switching over to 1.3 on Linux x64 and the game would save. But all the fmv’s and cut movies would glitch out and become pixelated. Worked on patching it for a couple days and finally gave up. 

I ended up just playing on Dosbox. Didn’t want to have to choose between saves or no videos.

**Comment by public-space** [comment]
Btw if you decide to play on Dosbox instead, only the original works. To install the full game, you need 640+ mb of free space and Dosbox Staging/X only allow 260mb.

I initially got my Fallout 1.1ce from the archive.org page for Native Linux gaming. Almost all the games worked very cleanly. Was very impressed. Tried to build it from here and built clean once again but only the save didn’t work
Still sadly. 

I even contemplated just leaving the game running till I completed it lol. 

@roustam What distro are you playing on? I tried it on Fedora and Ubuntu and faced that issue.

**Comment by roustam** [comment]
I managed to resolve the problem. 

After I tried February 2023 (version 1.0) x64 at the same directory, it complained about critter.dat file. I corrected the name and then old 1.0 version started normally. I was able to save and load my game without any errors.

Later I tried  March 2024  (1.1)  from same directory and the problem has gone. There might be something connected with file paths.

My system is  Debian GNU/Linux 12 (bookworm).

**Comment by hartmark** [comment]
I'm on steam deck. using Gog Fallout classic version

I cannot save either on 1.1 version, I downloaded 1.0 and it complained about missing CD, so I renamed MASTER.DAT and CRITTER.DAT to lowercase and then 1.0 worked and I can save.

I tried 1.1 again after that and I still cannot save, the save I saved in 1.0 doesn't show when trying to load.

Update:
rename MASTER.DAT and CRITTER.DAT and DATA folder to lowercase and it will work to save.
